services:
  app:
    profiles: [frontend]
    container_name: app
    build:
      context: packages/web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://api:8090
    restart: unless-stopped
  ollama:
    profiles: [backend]
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - 11434:11434
    container_name: ollama
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
  api:
    profiles: [backend]
    container_name: api
    build:
      context: packages/api
    ports:
      - "8090:8090"
    environment:
      - CHAT_PROVIDER=ollama
      - OLLAMA_MODEL=gemma3:1b
      - OLLAMA_BASE_URL=http://ollama:11434
      - AZURE_QNA_ENDPOINT=${AZURE_QNA_ENDPOINT}
      - AZURE_QNA_API_KEY=${AZURE_QNA_API_KEY}
      - AZURE_QNA_PROJECT_NAME=${AZURE_QNA_PROJECT_NAME}
      - AZURE_QNA_DEPLOYMENT_NAME=${AZURE_QNA_DEPLOYMENT_NAME}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    develop:
      watch:
        - action: rebuild
          path: .
